sources:
  - name: "내 보유 장서"
    module: "src.sources.local_books"
    class: "LocalBooksPlugin"
    priority: 1
    enabled: true
  - name: "공공도서관"
    priority: 2
    enabled: true
    module: "src.sources.library"
    class: "LibraryPlugin"
    libraries:
      - "111003"
      - "111030"
  - name: "싸피 e-book"
    priority: 3
    enabled: true
    module: "src.sources.ssafy_ebook"
    class: "SSAFYPlugin"
  - name: "리디 셀렉트"
    priority: 4
    enabled: true
    module: "src.sources.ridibooks_select"
    class: "RidibooksSelectPlugin"
  - name: "부커스"
    priority: 5
    enabled: true
    module: "src.sources.bookers"
    class: "BookersPlugin"
  - name: "구글 플레이북"
    priority: 6
    enabled: true
    module: "src.sources.google_play_books"
    class: "GooglePlayPlugin"
  - name: "알라딘 서점"
    priority: 7
    enabled: false
    module: "src.sources.aladin"
    class: "AladinPlugin"
